INSERT INTO sweetener (id, name) VALUES (1, 'D-말티톨');
INSERT INTO sweetener (id, name) VALUES (2, 'D-소비톨액');
INSERT INTO sweetener (id, name) VALUES (3, '나한과추출분말');
INSERT INTO sweetener (id, name) VALUES (4, '말티톨');
INSERT INTO sweetener (id, name) VALUES (5, '수크랄로스');
INSERT INTO sweetener (id, name) VALUES (6, '스테비아');
INSERT INTO sweetener (id, name) VALUES (7, '스테비올 배당체');
INSERT INTO sweetener (id, name) VALUES (8, '아라비아검');
INSERT INTO sweetener (id, name) VALUES (9, '아세설팜칼륨');
INSERT INTO sweetener (id, name) VALUES (10, '아스파탐');
INSERT INTO sweetener (id, name) VALUES (11, '알룰로스');
INSERT INTO sweetener (id, name) VALUES (12, '에리스리톨');
INSERT INTO sweetener (id, name) VALUES (13, '이소말트');
INSERT INTO sweetener (id, name) VALUES (14, '자일리톨');
INSERT INTO sweetener (id, name) VALUES (15, '효소처리스테비아');

INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (1, '저당팝콘 초코범벅 x 카라멜', '라칸스윗', '간식/디저트', 15450, 23, '저당류', 120, 1, 14);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (2, '딥 쿠키앤크림 프로틴바 (12입)', '퀘스트뉴트리션', '간식/디저트', 78500, 8, '저당류', 180, 1, 17);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (3, '다크 초콜릿 스타일 베이킹 칩', '릴리스', '간식/디저트', 18250, 41, '무당류', 50, 0, 8);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (4, '초콜릿 솔티드 카라멜 베이킹 칩', '릴리스', '간식/디저트', 17340, 17, '저당류', 60, 1, 8);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (5, '밀크 초콜릿 스타일 베이킹 칩', '릴리스', '간식/디저트', 18220, 0, '저당류', 60, 1, 8);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (6, '프로틴 드링크 퍼펙트 솔티드카라멜', '랩노쉬', '음료', 14820, 52, '무당류', 130, 0, 2);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (7, '프로틴 드링크 퍼펙트 멜론', '랩노쉬', '음료', 17900, 31, '무당류', 130, 0, 3);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (8, '프로틴 드링크 퍼펙트 쿠키앤크림', '랩노쉬', '음료', 12900, 26, '무당류', 130, 0, 3);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (9, '프로틴 밸런스 액티브 더블샷 커피 제로', '하이뮨', '음료', 25900, 12, '무당류', 104, 0, 7);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (10, '케토 바크 밀크 초콜릿 아몬드', 'ChocZero', '간식/디저트', 15000, 19, '저당류', 170, 2, 16);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (11, '다크 초콜릿칩', 'ChocZero', '간식/디저트', 70400, 5, '무당류', 60, 0, 8);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (12, '애플 민트 스파클링 제로', '배스킨라빈스', '탄산', 27080, 37, '무당류', 4, 0, 1);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (13, '제로 스파클링 배', '던킨도너츠', '탄산', 13550, 44, '무당류', 0, 0, 0);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (14, '슈가프리 클래식 카라멜 시럽', '토라니', '조미료/소스', 49400, 9, '무당류', 0, 0, 0.7);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (15, '클린 덴티제로 밸런스 구강유산균', '바이오움', '건강기능식품', 32000, 15, '저당류', 373, 1.3, 81.6);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (16, '저당 웨하스 초코', '스윗프리', '간식/디저트', 3200, 28, '저당류', 150, 4, 19);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (17, '무설탕 캔디 레몬맛', '스윗프리', '간식/디저트', 1000, 66, '무당류', 60, 0, 15);
INSERT INTO product (id, name, brand, category, price, stock, claim_type, kcal, sugar_g, carb_g) VALUES (18, '제로 스파클링 파인애플', '일화', '탄산', 1200, 120, '무당류', 0, 0, 0);

INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (1, 13);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (1, 5);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (2, 7);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (2, 5);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (2, 12);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (3, 12);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (3, 13);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (3, 7);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (4, 12);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (4, 13);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (4, 7);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (5, 12);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (5, 13);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (5, 7);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (6, 5);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (6, 9);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (7, 5);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (7, 9);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (8, 9);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (8, 5);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (9, 11);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (9, 5);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (9, 9);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (10, 3);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (11, 3);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (12, 9);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (12, 5);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (12, 10);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (13, 5);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (13, 9);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (13, 3);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (13, 10);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (14, 9);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (14, 5);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (15, 2);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (15, 14);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (15, 8);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (15, 15);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (16, 4);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (16, 5);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (17, 4);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (17, 10);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (18, 11);
INSERT INTO product_sweetener (product_id, sweetener_id) VALUES (18, 15);

INSERT INTO product_allergen (product_id, allergen) VALUES (2, '우유');
INSERT INTO product_allergen (product_id, allergen) VALUES (2, '대두');
INSERT INTO product_allergen (product_id, allergen) VALUES (3, '우유');
INSERT INTO product_allergen (product_id, allergen) VALUES (4, '우유');
INSERT INTO product_allergen (product_id, allergen) VALUES (5, '우유');
INSERT INTO product_allergen (product_id, allergen) VALUES (6, '우유');
INSERT INTO product_allergen (product_id, allergen) VALUES (7, '우유');
INSERT INTO product_allergen (product_id, allergen) VALUES (8, '우유');
INSERT INTO product_allergen (product_id, allergen) VALUES (9, '우유');
INSERT INTO product_allergen (product_id, allergen) VALUES (9, '대두');
INSERT INTO product_allergen (product_id, allergen) VALUES (10, '우유');
INSERT INTO product_allergen (product_id, allergen) VALUES (16, '밀');
INSERT INTO product_allergen (product_id, allergen) VALUES (16, '대두');
