[SERVICE]
    Flush        5
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name         tail
    Path         /var/lib/docker/containers/*/*-json.log
    Parser       docker
    Tag          docker.*
    Refresh_Interval 5
    Skip_Long_Lines On

[OUTPUT]
    Name         es
    Match        *
    Host         elasticsearch
    Port         9200
    Index        zeropick-logs
    Suppress_Type_Name On
    Replace_Dots On
    Trace_Error  On
